dataset:
  name: 'DK' #'UEA', 'DK', 'UCR'
  subset_name: 'Adiac'
  in_channels: 1
  data_scaling: True
  batch_size: 256
  num_workers: 1

exp_params:
  LR: 0.001  # learning rate
  weight_decay: 0.00001

trainer_params:
  accelerator: gpu # cpu or gpu
  devices: [0] # if cpu use auto
                # if gpu use auto or -1 for all gpus. For a subset use e.g.
                # 3 --> [0,1,2] or just list them [0,1,3,4] if gpu0 then [0]
  max_epochs: 1000

